# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: Asp Dot Net Core
    inputs:
     command: build
     projects: '**/FirstDotNetApplication/*.csproj'
     configuration: ${buildConfiguration}

  - task: DotNetCoreCLI@2
    displayName: 'Run Test First'
    inputs:
     command: test
     arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true'
     publishTestResults: true
     projects: '**/FirstDotNetApplication_UnitTest/*.csproj'