// <auto-generated />
using System;
using FirstDotNetApplication_DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstDotNetApplication_DataLayer.Migrations
{
    [DbContext(typeof(DbPaymentProcess))]
    [Migration("20201206165435_PaymentGatewayInitialMigration")]
    partial class PaymentGatewayInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FirstDotNetApplication_DataLayer.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardHolderName");

                    b.Property<string>("CreditCardNumber");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FirstDotNetApplication_DataLayer.PaymentInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("CardHolderName");

                    b.Property<string>("CreditCardNumber");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("SecurityCode");

                    b.HasKey("Id");

                    b.ToTable("PaymentInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
